name: facebook_dart_sdk
description: Facebook Dart SDK
dependencies:
  browser: any
  http: '>=0.11.1+1 <0.12.0'
  logging: '>=0.9.0 <0.10.0'
  smoke: '>=0.2.1+1 <0.3.0'
  intl: any
dev_dependencies:
  unittest: '>=0.10.0 <0.10.1'